### ISSUE TITLE
Item "Leave" cannot be translated.

### ISSUE THREAD

**Issue by LazoYoung** [ObelusPA/CreativeParkour#2]
When you play a map you will have the item in 9th hotbar slot.
I tried to translate its name however i couldn't find the key phrase in translation file.
This is a minor one but i'd like to see this solved asap

**Comment by ObelusPA** [comment]
Hello! Sorry for the late reply, but the phrase used for this item is "commands.leave" (the first word if there are command aliases), because it is supposed to be the same word.
Is it ok or do you want a separate phrase? I can add it if you want.

**Comment by LazoYoung** [comment]
Yes I would like to see it separated thank you

**Comment by ObelusPA** [comment]
I added a new "play.items.leave" phrase in the new update. 🙂
