### ISSUE TITLE
Ghost Data not being sent to creativeparkour.net

### ISSUE THREAD

**Issue by James76931** [ObelusPA/CreativeParkour#6]
Hi,

For some reason Ghost Data from my server is not being uploaded to Creativeparkour.net and there are no logs telling me why.

Another server which runs Creativeparkour was also not sending ghost data to the website however was able to download the map which makes me believe that this is an issue on the website with receiving Ghost Data.

_- James_

**Comment by ObelusPA** [comment]
Hi! Can you give me the name of the map and a player to check if the website received something? Sometimes it takes time for the website to validate ghosts, but the queue is empty right now, so the problem may be somewhere else.
Also, if it is for your "Redstone" map, since you uploaded it several times, only ghosts from the last version of the map will be saved on the website.

**Comment by James76931** [comment]
Hi!
The map was Redstone and I played on the map as the username "James76931". I have been deleting older versions from the site and ensuring there are no old versions of the map on the server.

**Comment by ObelusPA** [comment]
It works, your ghost has been uploaded and is in the leaderboard: https://creativeparkour.net/map.php?id=320
I do not think there is any problem with this.

**Comment by James76931** [comment]
Ah ok. For some reason it wasn't showing up for me after I tried reuploading them so I guess I didn't wait long enough. Thank you! :)

**Comment by James76931** [comment]
Hm, I uploaded an update for the same map a few hours ago and it still hasn't appeared on the website for some reason. I don't think it would take multiple hours to process the ghost data, so maybe the issue has came back?

**Comment by ObelusPA** [comment]
It can take several hours when I have to manually validate ghosts. In your case you are the first one in the map so it is not automatically validated, I will do it as soon as possible.
I made this system to avoid cheaters, but don’t worry, all your ghosts will appear, there are no false positives. 🙂

Le 15 oct. 2017 à 06:28, James76931 <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hm, I uploaded an update for the same map a few hours ago and it still hasn't appeared on the website for some reason. I don't think it would take multiple hours to process the ghost data, so maybe the issue has came back?

**Comment by ObelusPA** [comment]
It can take several hours when I have to manually validate ghosts. In your case you are the first one in the map so it is not automatically validated, I will do it as soon as possible.
I made this system to avoid cheaters, but don’t worry, all your ghosts will appear, there are no false positives. 🙂

**Comment by James76931** [comment]
Ah ok, I didn't realise that there was a manual approval process. Thanks! :)
