### ISSUE TITLE
Why are you restoring the inventory after 2 ticks?

### ISSUE THREAD

**Issue by RoboMWM** [ObelusPA/CreativeParkour#9]
So I wrote my own inventory save and restorer, but unless I make it wait like at least 3 ticks before restoring, your plugin will take over and restore whatever it thinks it should restore (which in some cases might be an empty inventory!)

This wouldn't be an issue if you'd just runTask()/schedule it 1 tick later. But anyways, I've found out how to disable the inventory restorer, and upon testing it seems to work okay. So at this point I'm just curious why you wait 2 ticks instead of 1.

**Comment by ObelusPA** [comment]
Hi!
When I made this (a long time ago), many users had problems with their inventories not being restored, there was conflicts with other plugins that replaced inventories during the first tick, so I made CreativeParkour wait 2 ticks to make sure inventories are not lost but there was still the option to disable this feature for users that want to use their own inventory restorer.
